### ISSUE TITLE
I loved it! Is it possible to add the data for each district? 

### ISSUE THREAD

**Issue by aaryandewan** [kousiksatish/covidindia-cli#1]
It would be pretty cool if `covidindia-cli maharashtra` returns the data of the whole state **plus** the data of each district.

**Comment by kousiksatish** [comment]
Sure... That was my next plan. Will add it by EOD

**Comment by aaryandewan** [comment]
Great! Eagerly waiting for it :)

**Comment by kousiksatish** [comment]
Will keep this open and close it with the PR
