### ISSUE TITLE
Add sort by option to the CLI

### ISSUE THREAD

**Issue by kousiksatish** [kousiksatish/covidindia-cli#4]

**Comment by sidtr0** [comment]
How will this sort by option work? Could you elaborate please?

**Comment by kousiksatish** [comment]
covidindia-cli -s active
covidindia-cli -s deceased
covidindia-cli -s confirmed

Should sort appropriately based on those numbers.

Checkout options in yargs documentation.

Do you wish to work on this?

**Comment by sidtr0** [comment]
I'm not too familiar with yargs (or CLI-based  nodejs apps in general) but I would love to assist you in any way possible. 

I'll fork the repo on Sunday and see if I can do something.

**Comment by kousiksatish** [comment]
@Drac5079 Sure! Please let me know if you need any help.

You can refer corona-cli project which has a similar feature

**Comment by sidtr0** [comment]
Okay, I will do so in the afternoon when I’m free.
